### ISSUE TITLE
Pretty-printing multiple contract heads

### ISSUE THREAD

**Issue by evnu** [asummers/erlex#3]
When multiple contract heads are encountered, the output would be more reasonable if newline separated the contract heads.

Example from [pretty_print_test.exs](https://github.com/asummers/erlex/blob/889e0edb6a47bd7063faec3e6dffcdef4e9c92b2/test/pretty_print_test.exs#L294)

```elixir
expected_output =
  "Contract head: (any(), nil) :: nilContract head: (Ecto.Queryable.t(), String.t()) :: String.t()"
```

I believe this to be more readable if it includes an additional newline:

```elixir
expected_output =
  "Contract head: (any(), nil) :: nil\nContract head: (Ecto.Queryable.t(), String.t()) :: String.t()"
```

**Comment by asummers** [comment]
That sounds totally reasonable.

**Comment by evnu** [comment]
I can provide a pull request if you'd like to delegate that.

**Comment by asummers** [comment]
This has been published to [Hex](https://hex.pm/packages/erlex). It will be bumped in Dialyxir when I fix something else in that project, but you should be able to do `mix deps.update erlex` and have it bump in your `mix.lock` file without issue, as that only depends on `~> 0.1` for this library. Thanks again!
